
version: "3"
services:
  python:
    image: cloudpassage/devel:latest
    command: /bin/bash -c "cd /home/user/CloudpassageAPI && git pull && tail -f /dev/null"
    hostname: cloudpassage
    tty: True
    volumes:
      - ./../:/localDir/:consistent
    networks:
      - cloud-net

networks:
  cloud-net:
