FROM centos:7

#Install packages

#Set root password
RUN echo "root:password" |chpasswd

#install PIP
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
RUN python get-pip.py

#Create user
RUN useradd -m user

# User specific settings
USER user
WORKDIR /home/user